import { describe, expect, it } from 'vitest'
import { readFileSync } from 'node:fs'
import { fileURLToPath } from 'node:url'

import tileImageViewerSource from './index.tsx?raw'

const tileImageViewerCss = readFileSync(fileURLToPath(new URL('./TileImageViewer.css', import.meta.url)), 'utf8')

describe('TileImageViewer QML hover point-value parity', () => {
  it('can draw QML non-AREA 2D source images without tile URL mutation', () => {
    expect(tileImageViewerSource).toContain('tiled = true')
    expect(tileImageViewerSource).toContain('if (!tiled) {')
    expect(tileImageViewerSource).toContain('const sourceImage = tileCache.get(imageUrl)')
    expect(tileImageViewerSource).toContain('ctx.drawImage(sourceImage, 0, 0, imageInfo.width, imageInfo.height)')
    expect(tileImageViewerSource).toContain('if (tiled) {')
    expect(tileImageViewerSource).toContain('buildTileUrl(imageUrl, tile, tileCount)')
  })

  it('requests QML heightPoint values for the hovered image pixel before rendering the point HUD', () => {
    expect(tileImageViewerSource).toContain('pointValueShowType')
    expect(tileImageViewerSource).toContain('pointValueOptions')
    expect(tileImageViewerSource).toContain('requestHeightPointByWebSocket')
    expect(tileImageViewerSource).toContain('heightDataApi.getHeightPoint(surfaceKey, coilId,')
    expect(tileImageViewerSource).toContain('.catch(() => heightDataApi.getHeightPoint(surfaceKey, coilId, point))')
    expect(tileImageViewerSource).toContain('buildQmlHoverPointInfo')
    expect(tileImageViewerSource).toContain('data-point-value-hud={hoverPoint ?')
    expect(tileImageViewerSource).toContain('className="tile-point-value-hud"')
  })

  it('keeps the QML point-value HUD as a floating non-interactive overlay', () => {
    expect(tileImageViewerCss).toContain('.tile-point-value-hud')
    expect(tileImageViewerCss).toMatch(/\.tile-point-value-hud\s*\{[\s\S]*position:\s*absolute/)
    expect(tileImageViewerCss).toMatch(/\.tile-point-value-hud\s*\{[\s\S]*pointer-events:\s*none/)
    expect(tileImageViewerCss).toMatch(/\.tile-point-value-hud\s*\{[\s\S]*white-space:\s*nowrap/)
  })

  it('accepts QML ScaleBtn and GammaBtn values from the DataShow header', () => {
    expect(tileImageViewerSource).toContain('canvasScale?: number | null')
    expect(tileImageViewerSource).toContain('imageGamma?: number | null')
    expect(tileImageViewerSource).toContain('onQmlScaleMetricsChange?: (metrics: QmlScaleMetrics) => void')
    expect(tileImageViewerSource).toContain('normalizeQmlCanvasScale(canvasScale)')
    expect(tileImageViewerSource).toContain('normalizeQmlImageGamma(imageGamma)')
    expect(tileImageViewerSource).toContain('buildCenteredScaleTransform({')
    expect(tileImageViewerSource).toContain('onQmlScaleMetricsChange?.(nextMetrics)')
    expect(tileImageViewerSource).toContain('applyTransform(nextTransform, true, nextTransform.scale)')
    expect(tileImageViewerSource).toContain("data-canvas-scale={normalizedCanvasScale?.toFixed(2) ?? 'auto'}")
    expect(tileImageViewerSource).toContain('data-qml-min-scale={qmlScaleMetrics.minScale.toFixed(2)}')
    expect(tileImageViewerSource).toContain("data-image-gamma={normalizedImageGamma?.toFixed(2) ?? 'none'}")
    expect(tileImageViewerSource).toContain("ctx.filter = `brightness(${normalizedImageGamma})`")
    expect(tileImageViewerSource).toContain("ctx.filter = 'none'")
  })

  it('notifies QML scale metrics outside the React state updater', () => {
    expect(tileImageViewerSource).toContain('const qmlScaleMetricsRef = useRef<QmlScaleMetrics>')
    expect(tileImageViewerSource).toContain('qmlScaleMetricsRef.current = nextMetrics')
    expect(tileImageViewerSource).toContain('setQmlScaleMetrics(nextMetrics)')

    const metricsStateUpdateStart = tileImageViewerSource.indexOf('setQmlScaleMetrics(')
    const metricsNotifyIndex = tileImageViewerSource.indexOf('onQmlScaleMetricsChange?.(nextMetrics)')

    expect(metricsStateUpdateStart).toBeGreaterThan(-1)
    expect(metricsNotifyIndex).toBeGreaterThan(metricsStateUpdateStart)
    expect(tileImageViewerSource).not.toContain('setQmlScaleMetrics((current) => {')
  })

  it('supports QML lockControl shared view bindings with a controlled transform', () => {
    expect(tileImageViewerSource).toContain('export interface TileImageViewerTransform')
    expect(tileImageViewerSource).toContain('controlledTransform?: TileImageViewerTransform | null')
    expect(tileImageViewerSource).toContain('onTransformChange?: (transform: TileImageViewerTransform) => void')
    expect(tileImageViewerSource).toContain('const applyTransform = useCallback(')
    expect(tileImageViewerSource).toContain('onTransformChange?.(nextTransform)')
    expect(tileImageViewerSource).toContain('if (!controlledTransform || !imageInfo.ready) return')
    expect(tileImageViewerSource).toContain('applyTransform(controlledTransform, false)')
    expect(tileImageViewerSource).toContain("data-qml-transform-controlled={controlledTransform ? 'true' : 'false'}")
  })

  it('mirrors QML ShowInfos as a non-interactive image information overlay', () => {
    expect(tileImageViewerSource).toContain('qmlXToMmText')
    expect(tileImageViewerSource).toContain('qmlYToMmText')
    expect(tileImageViewerSource).toContain('const qmlShowInfos = useMemo')
    expect(tileImageViewerSource).toContain('data-qml-show-infos')
    expect(tileImageViewerSource).toContain('data-qml-show-info="hover-x"')
    expect(tileImageViewerSource).toContain('data-qml-show-info="hover-y"')
    expect(tileImageViewerSource).toContain('data-qml-show-info="width-mm"')
    expect(tileImageViewerSource).toContain('data-qml-show-info="height-mm"')
    expect(tileImageViewerSource).toContain('data-qml-show-info="source-px"')
    expect(tileImageViewerSource).toContain('data-qml-show-info="tile-px"')
    expect(tileImageViewerSource).toContain('data-qml-show-info="display-px"')
    expect(tileImageViewerSource).toContain('Math.trunc(sourceWidth / tileCount)')
    expect(tileImageViewerCss).toMatch(/\.tile-show-infos\s*\{[\s\S]*position:\s*absolute/)
    expect(tileImageViewerCss).toMatch(/\.tile-show-infos\s*\{[\s\S]*pointer-events:\s*none/)
    expect(tileImageViewerCss).toMatch(/\.tile-image-hud\s*\{[\s\S]*right:\s*12px/)
    expect(tileImageViewerCss).toMatch(/\.tile-show-info-value\s*\{[\s\S]*background:\s*rgba\(46,\s*46,\s*46,\s*0\.47\)/)
  })

  it('mirrors QML AerialView as a hover-brightened image overview', () => {
    expect(tileImageViewerSource).toContain('showAerialView?: boolean')
    expect(tileImageViewerSource).toContain('buildQmlAerialView')
    expect(tileImageViewerSource).toContain('buildQmlAerialTargetTransform')
    expect(tileImageViewerSource).toContain('data-qml-aerial-view')
    expect(tileImageViewerSource).toContain('data-qml-aerial-viewport')
    expect(tileImageViewerCss).toMatch(/\.tile-aerial-view\s*\{[\s\S]*width:\s*100px/)
    expect(tileImageViewerCss).toMatch(/\.tile-aerial-view\s*\{[\s\S]*background:\s*rgba\(0,\s*0,\s*0,\s*0\.14\)/)
    expect(tileImageViewerCss).toMatch(/\.tile-image-viewer\s*\{[\s\S]*overflow:\s*visible/)
    expect(tileImageViewerCss).toMatch(/\.tile-aerial-view:hover\s+\.tile-aerial-image\s*\{[\s\S]*opacity:\s*1/)
    expect(tileImageViewerCss).toMatch(/\.tile-aerial-viewport\s*\{[\s\S]*border:\s*1px\s+solid\s+blue/)
  })

  it('mirrors QML CrossView hover crosshair and coordinate labels for 2D views', () => {
    expect(tileImageViewerSource).toContain('showQmlCrossView?: boolean')
    expect(tileImageViewerSource).toContain('crossWarningThresholdUp?: number')
    expect(tileImageViewerSource).toContain('crossWarningThresholdDown?: number')
    expect(tileImageViewerSource).toContain('getQmlCrossViewZColor')
    expect(tileImageViewerSource).toContain('data-qml-cross-view')
    expect(tileImageViewerSource).toContain('data-qml-cross-line="horizontal"')
    expect(tileImageViewerSource).toContain('data-qml-cross-line="vertical"')
    expect(tileImageViewerSource).toContain('data-qml-cross-label="y-mm"')
    expect(tileImageViewerSource).toContain('data-qml-cross-label="x-mm"')
    expect(tileImageViewerSource).toContain('data-qml-cross-label="z"')
    expect(tileImageViewerSource).toContain('left: hoverPoint.screen.x')
    expect(tileImageViewerSource).toContain('top: hoverPoint.screen.y')
    expect(tileImageViewerCss).toMatch(/\.tile-qml-cross-view\s*\{[\s\S]*position:\s*absolute/)
    expect(tileImageViewerCss).toMatch(/\.tile-qml-cross-view\s*\{[\s\S]*pointer-events:\s*none/)
    expect(tileImageViewerCss).toMatch(/\.tile-qml-cross-line\.horizontal\s*\{[\s\S]*width:\s*20px/)
    expect(tileImageViewerCss).toMatch(/\.tile-qml-cross-line\.horizontal\s*\{[\s\S]*left:\s*-10px/)
    expect(tileImageViewerCss).toMatch(/\.tile-qml-cross-line\.vertical\s*\{[\s\S]*height:\s*20px/)
    expect(tileImageViewerCss).toMatch(/\.tile-qml-cross-line\.vertical\s*\{[\s\S]*top:\s*-10px/)
    expect(tileImageViewerCss).toMatch(/\.tile-qml-cross-label\s*\{[\s\S]*background:\s*#000/)
    expect(tileImageViewerCss).toMatch(/\.tile-qml-cross-label\s*\{[\s\S]*border-radius:\s*5px/)
    expect(tileImageViewerCss).toMatch(/\.tile-qml-cross-label\.coordinate\s*\{[\s\S]*color:\s*red/)
    expect(tileImageViewerCss).toMatch(/\.tile-qml-cross-label\.z-safe\s*\{[\s\S]*color:\s*green/)
    expect(tileImageViewerCss).toMatch(/\.tile-qml-cross-label\.z-warning\s*\{[\s\S]*color:\s*red/)
  })

  it('mirrors QML DrawSurvey as a click-defined 2D measurement overlay', () => {
    expect(tileImageViewerSource).toContain("mouseTool?: 'move' | 'survey'")
    expect(tileImageViewerSource).toContain('buildQmlSurveyOverlay')
    expect(tileImageViewerSource).toContain('const [qmlSurveyState, setQmlSurveyState]')
    expect(tileImageViewerSource).toContain('handleQmlSurveyPointer')
    expect(tileImageViewerSource).toContain("state: 'running'")
    expect(tileImageViewerSource).toContain("state: 'end'")
    expect(tileImageViewerSource).toContain('setQmlSurveyState(null)')
    expect(tileImageViewerSource).toContain('data-qml-draw-survey')
    expect(tileImageViewerSource).toContain('data-qml-survey-state={qmlSurveyState.state}')
    expect(tileImageViewerSource).toContain('data-qml-survey-corner')
    expect(tileImageViewerSource).toContain('data-qml-survey-diagonal')
    expect(tileImageViewerSource).toContain('data-qml-survey-label="width"')
    expect(tileImageViewerSource).toContain('data-qml-survey-label="height"')
    expect(tileImageViewerSource).toContain('data-qml-survey-label="diagonal"')
    expect(tileImageViewerCss).toMatch(/\.tile-qml-survey\s*\{[\s\S]*position:\s*absolute/)
    expect(tileImageViewerCss).toMatch(/\.tile-qml-survey\s*\{[\s\S]*pointer-events:\s*none/)
    expect(tileImageViewerCss).toMatch(/\.tile-qml-survey-path\s*\{[\s\S]*stroke:\s*red/)
    expect(tileImageViewerCss).toMatch(/\.tile-qml-survey-corner\s*\{[\s\S]*stroke-dasharray:\s*5\s+5/)
    expect(tileImageViewerCss).toMatch(/\.tile-qml-survey-label\s*\{[\s\S]*background:\s*#000/)
    expect(tileImageViewerCss).toMatch(/\.tile-qml-survey-label\.height\s*\{[\s\S]*transform:\s*translateY\(-50%\)\s+rotate\(90deg\)/)
  })

  it('mirrors QML UserPointShow by adding sign points on move-mode double click', () => {
    expect(tileImageViewerSource).toContain('enableQmlUserPoints?: boolean')
    expect(tileImageViewerSource).toContain('qmlUserPoints?: QmlUserPointState[]')
    expect(tileImageViewerSource).toContain('onQmlUserPointsChange?: (update: QmlUserPointUpdate) => void')
    expect(tileImageViewerSource).toContain('buildQmlUserPointOverlay')
    expect(tileImageViewerSource).toContain('export interface QmlUserPointState')
    expect(tileImageViewerSource).toContain('const [internalQmlUserPoints, setInternalQmlUserPoints]')
    expect(tileImageViewerSource).toContain('const activeQmlUserPoints = qmlUserPoints ?? internalQmlUserPoints')
    expect(tileImageViewerSource).toContain('applyQmlUserPointsChange')
    expect(tileImageViewerSource).toContain('handleQmlUserPointDoubleClick')
    expect(tileImageViewerSource).toContain('onDoubleClick={handleQmlUserPointDoubleClick}')
    expect(tileImageViewerSource).toContain("mouseTool === 'move'")
    expect(tileImageViewerSource).toContain('heightDataApi.getHeightPoint(surfaceKey, coilId, point)')
    expect(tileImageViewerSource).toContain('applyQmlUserPointsChange((points) => [...points, { id, point, rawValue: 0 }])')
    expect(tileImageViewerSource).toContain('applyQmlUserPointsChange((points) =>')
    expect(tileImageViewerSource).toContain('data-qml-user-point')
    expect(tileImageViewerSource).toContain('data-qml-user-point-marker')
    expect(tileImageViewerSource).toContain('data-qml-user-point-label')
    expect(tileImageViewerCss).toMatch(/\.tile-qml-user-point\s*\{[\s\S]*position:\s*absolute/)
    expect(tileImageViewerCss).toMatch(/\.tile-qml-user-point\s*\{[\s\S]*pointer-events:\s*none/)
    expect(tileImageViewerCss).toMatch(/\.tile-qml-user-point-marker\s*\{[\s\S]*width:\s*8px/)
    expect(tileImageViewerCss).toMatch(/\.tile-qml-user-point-marker\s*\{[\s\S]*border:\s*2px\s+solid\s+green/)
    expect(tileImageViewerCss).toMatch(/\.tile-qml-user-point-label\s*\{[\s\S]*color:\s*yellow/)
  })

  it('mirrors QML DbPointShow as a database point overlay layer', () => {
    expect(tileImageViewerSource).toContain('qmlDbPoints?: QmlDbPointSource[]')
    expect(tileImageViewerSource).toContain('buildQmlDbPointOverlay')
    expect(tileImageViewerSource).toContain('normalizeQmlDbPoint')
    expect(tileImageViewerSource).toContain('const qmlDbPointOverlays = useMemo')
    expect(tileImageViewerSource).toContain('data-qml-db-point')
    expect(tileImageViewerSource).toContain('data-qml-db-point-marker')
    expect(tileImageViewerSource).toContain('data-qml-db-point-label')
    expect(tileImageViewerCss).toMatch(/\.tile-qml-db-point\s*\{[\s\S]*position:\s*absolute/)
    expect(tileImageViewerCss).toMatch(/\.tile-qml-db-point\s*\{[\s\S]*pointer-events:\s*none/)
    expect(tileImageViewerCss).toMatch(/\.tile-qml-db-point-marker\s*\{[\s\S]*width:\s*4px/)
    expect(tileImageViewerCss).toMatch(/\.tile-qml-db-point-marker\s*\{[\s\S]*border:\s*2px\s+solid\s+red/)
    expect(tileImageViewerCss).toMatch(/\.tile-qml-db-point-label\s*\{[\s\S]*color:\s*yellow/)
    expect(tileImageViewerCss).toMatch(/\.tile-qml-db-point-label\.warning\s*\{[\s\S]*color:\s*red/)
  })

  it('mirrors QML DrawView height-line and inner-ellipse overlays on image views', () => {
    expect(tileImageViewerSource).toContain('qmlDrawViewLineSegments?: HeightLineSegment[]')
    expect(tileImageViewerSource).toContain('qmlDrawViewInnerEllipse?: QmlDbPointInnerEllipse | null')
    expect(tileImageViewerSource).toContain('qmlDrawViewPerpendicularLine?: QmlDrawViewPerpendicularLine | null')
    expect(tileImageViewerSource).toContain('qmlDrawViewTaperEnabled?: boolean')
    expect(tileImageViewerSource).toContain('buildQmlDrawViewOverlay')
    expect(tileImageViewerSource).toContain('const qmlDrawViewOverlay = useMemo')
    expect(tileImageViewerSource).toContain('taperSegmentsEnabled: qmlDrawViewTaperEnabled')
    expect(tileImageViewerSource).toContain('hoverPoint: hoverPoint?.point')
    expect(tileImageViewerSource).toContain('data-qml-draw-view')
    expect(tileImageViewerSource).toContain('data-qml-draw-line')
    expect(tileImageViewerSource).toContain('data-qml-draw-taper-line')
    expect(tileImageViewerSource).toContain('data-qml-draw-ellipse')
    expect(tileImageViewerSource).toContain('data-qml-draw-axis="major"')
    expect(tileImageViewerSource).toContain('data-qml-draw-axis="minor"')
    expect(tileImageViewerSource).toContain('data-qml-draw-label="major"')
    expect(tileImageViewerSource).toContain('data-qml-draw-label="minor"')
    expect(tileImageViewerSource).toContain('data-qml-draw-perpendicular-point')
    expect(tileImageViewerCss).toMatch(/\.tile-qml-draw-view\s*\{[\s\S]*position:\s*absolute/)
    expect(tileImageViewerCss).toMatch(/\.tile-qml-draw-view\s*\{[\s\S]*pointer-events:\s*none/)
    expect(tileImageViewerCss).toMatch(/\.tile-qml-draw-line\s*\{[\s\S]*stroke:\s*blue/)
    expect(tileImageViewerCss).toMatch(/\.tile-qml-draw-line\s*\{[\s\S]*stroke-dasharray:\s*10\s+5/)
    expect(tileImageViewerCss).toMatch(/\.tile-qml-draw-taper-line\s*\{[\s\S]*stroke:\s*red/)
    expect(tileImageViewerCss).toMatch(/\.tile-qml-draw-ellipse\s*\{[\s\S]*stroke:\s*green/)
    expect(tileImageViewerCss).toMatch(/\.tile-qml-draw-axis\s*\{[\s\S]*stroke-dasharray:\s*2\s+2/)
    expect(tileImageViewerCss).toMatch(/\.tile-qml-draw-label\s*\{[\s\S]*color:\s*green/)
    expect(tileImageViewerCss).toMatch(/\.tile-qml-draw-label\s*\{[\s\S]*font-weight:\s*700/)
    expect(tileImageViewerCss).toMatch(/\.tile-qml-draw-perpendicular-point\s*\{[\s\S]*width:\s*4px/)
    expect(tileImageViewerCss).toMatch(/\.tile-qml-draw-perpendicular-point\s*\{[\s\S]*border:\s*2px\s+solid\s+orange/)
  })
})
