/*
 * This file is automatically generated by Qt Design Studio.
 * Do not change.
*/

#include <QtQml/qqmlextensionplugin.h>

// QML modules are embedded via resources, no plugin import required.
//Q_IMPORT_QML_PLUGIN(MotionStudioPlugin)
//Q_IMPORT_QML_PLUGIN(Quick3DAssets_BallBearing1Plugin)

